dashboard/forms.py
from flask_wtf import FlaskForm
from wtforms import RadioField, SubmitField, StringField
from wtforms.validators import DataRequired, Length

class VoteForm(FlaskForm):
    candidates = RadioField('Candidate', choices = [('candidate1', 'Candidate 1'), ('candidate2', 'Candidate 2'), ('candidate3', 'Candidate 3')], validators = [DataRequired()])
    private_key = StringField('Private Key', validators = [DataRequired(), Length(min = 64, max = 64)])
    submit = SubmitField('Submit')

class RegisterForm(FlaskForm):
    first_name = StringField('Name', validators = [DataRequired()])
    last_name = StringField('Last Name', validators = [DataRequired()])
    username = StringField('Username', validators = [DataRequired(), Length(min = 4, max = 20)])
    submit = SubmitField('Submit')

dashboard/__init__.py
from flask import Blueprint

dashboard = Blueprint('dashboard', __name__, template_folder='templates')

from . import routes

dashboard/routes.py
from . import dashboard
from flask import render_template, request
from .forms import *
from blockchain.transaction import Transaction
from blockchain.block import Block
from blockchain.blockchain import Blockchain
from blockchain.keys import Keys
from utils.users import User
import sqlite3
import os

blockchain = Blockchain()
keys = Keys()
user = User(sqlite3.connect("users.db", check_same_thread = False))

if os.path.isfile("blockchain.db"):
    blockchain.import_chain("blockchain")

@dashboard.route('/', methods = ['GET', 'POST'])
def index():
    form = VoteForm()
    if request.method == "POST" and form.validate_on_submit():
        if user.get_by_public_key(keys.get_public_key(form.private_key.data)) == None:
            return {
                "error": "Unregistered private key"
            }
        
        if blockchain.view_transaction_by_public_key(keys.get_public_key(form.private_key.data)) != None:
            return {
                "error": "Already voted"
            }

        transaction = Transaction(form.candidates.data, index = 0, private_key = form.private_key.data)
        block = Block([transaction], blockchain.get_previous_block_hash(), None, index = blockchain.get_next_index())
        block.nonce = block.calculate_block_nonce()
        blockchain.add_block(block)
        if blockchain.validate_chain():
            blockchain.export_chain("blockchain")
        return render_template('vote_added.html', block_hash = block.block_hash, transaction_hash = transaction.transaction_hash)
    return render_template('vote.html', form = form, is_valid = blockchain.validate_chain())

@dashboard.route('/view_results')
def results():
    results = {}
    for block in blockchain.chain:
        for transaction in block.transactions:
            if transaction.data in results:
                results[transaction.data] += 1
            else:
                results[transaction.data] = 1
    return render_template('results.html', results = results, is_valid = blockchain.validate_chain())

@dashboard.route("/register", methods = ['GET', 'POST'])
def register():
    form = RegisterForm()
    if request.method == "POST" and form.validate_on_submit():
        if user.get_user_by_username(form.username.data):
            return "User already exists"
        generated_keys = keys.generate_keys()
        user.create_user(form.username.data, form.first_name.data, form.last_name.data, generated_keys["public_key"])
        return render_template('valid_register.html', private_key = generated_keys["private_key"])
    return render_template('register.html', form = form)

@dashboard.route("/view/<block_hash>/<transaction_hash>")
def view_transaction(block_hash, transaction_hash):
    transaction = blockchain.view_transaction(block_hash, transaction_hash)
    return render_template('view_transaction.html', transaction = transaction.transaction_values())

dashboard/templates/base.html
<!doctype html>
<html lang='en'>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1'>
        <title>Tailwind</title>
        <script src='https://cdn.tailwindcss.com'></script>
    </head>
    <body>
        {% block content %}{% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
        {% block javascript %}{% endblock %}
    </body>
</html>

dashboard/templates/register.html
{% extends "base.html" %}

{% block content %}
<form method="POST" class="max-w-2xl border p-3 mx-auto my-16 rounded">

    <h3 class="text-3xl">Register</h3>
    {{ form.csrf_token }}
    <div class="mt-3">
        {{ form.first_name(class="mt-2.5 w-full border rounded py-1 px-2.5 focus:outline-gray-300", placeholder="First Name") }}
        {{ form.last_name(class="mt-2.5 w-full border rounded py-1 px-2.5 focus:outline-gray-300", placeholder="Last Name") }}
        {{ form.username(class="mt-2.5 w-full border rounded py-1 px-2.5 focus:outline-gray-300", placeholder="Username") }}
        <div class="flex items-center justify-start space-x-3 mt-2.5">
            <a href="{{ url_for('dashboard.index') }}" class="border px-5 py-1 rounded hover:bg-gray-200 ease duration-200">Return</a>
            {{ form.submit(class="w-full border bg-gray-100 rounded py-1 px-2.5 focus:outline-gray-300") }}

        </div>
    </div>
</form>
{% endblock %}

dashboard/templates/results.html
{% extends "base.html" %}
{% block content %}
<div class="max-w-5xl mx-auto p-3 my-24">
    <a href="{{ url_for('dashboard.index') }}" class="border px-5 py-1 rounded hover:bg-gray-200 ease duration-200">Return</a>
    <div class="grid grid-cols-3 gap-2.5 mt-5">
        {% for candidate in results %}
            <div class="border w-full p-4 rounded">
                <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png" class="rounded-full h-32 d-block mx-auto">
                <h4 class="text-center mt-5">{{candidate}}</h4>
                <p class="text-center">Votes: {{ results[candidate] }}</p>
            </div>
        {% endfor %}
    </div>
    {% if is_valid == true %}
        <div class="w-full p-3 my-5 rounded border border-green-500 bg-green-600 text-white">
            <p>Blockchain is valid.</p>
        </div>
    {% else %}
        <div class="w-full p-3 my-5 rounded border border-red-500 bg-red-600 text-white">
            <p>Blockchain is invalid results may be inaccurate.</p>
        </div>
    {% endif %}
</div>
{% endblock %}

dashboard/templates/thankyou.html
{% extends "base.html" %}
{% block content %}

<div class="max-w-5xl border mx-auto p-3 my-5">
    
    <div class="flex items-center space-x-3">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8 text-green-600">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 0 1-1.043 3.296 3.745 3.745 0 0 1-3.296 1.043A3.745 3.745 0 0 1 12 21c-1.268 0-2.39-.63-3.068-1.593a3.746 3.746 0 0 1-3.296-1.043 3.745 3.745 0 0 1-1.043-3.296A3.745 3.745 0 0 1 3 12c0-1.268.63-2.39 1.593-3.068a3.745 3.745 0 0 1 1.043-3.296 3.746 3.746 0 0 1 3.296-1.043A3.746 3.746 0 0 1 12 3c1.268 0 2.39.63 3.068 1.593a3.746 3.746 0 0 1 3.296 1.043 3.746 3.746 0 0 1 1.043 3.296A3.745 3.745 0 0 1 21 12Z" />
        </svg>
        <h3 class="text-3xl">Your vote has been added to the chain.</h3>
    </div>  
    <div class="my-3">
        <p class="font-mono">Block Hash: {{ block_hash }}</p>
        <p class="font-mono">Transaction Hash: {{ transaction_hash }}</p>
        <a href='{{ url_for("dashboard.view_transaction", block_hash = block_hash, transaction_hash = transaction_hash) }}' class="text-blue-600 underline">View Transaction</a>
        
    </div>
</div>
{% endblock %}

dashboard/templates/transaction.html
{% extends "base.html" %}

{% block content %}
<div class="max-w-3xl mx-auto my-5">
    <a href="{{ url_for('dashboard.index') }}" class="border px-5 py-1 rounded hover:bg-gray-200 ease duration-200">Return</a>
    <div class="border p-3 my-5">
        <div class="mb-3">
            <p class="text-gray-600 font-semibold">Transaction Hash</p>
            <h3 class="truncate text-2xl leading-5">{{ transaction["transaction_hash"] }}</h3>
        </div>
        <div class="mb-3">
            <p class="text-gray-600 font-semibold">Owner</p>
            <h3 class="truncate text-2xl leading-5">{{ transaction["public_key"] }}</h3>
        </div>
        <div class="mb-3">
            <p class="text-gray-600 font-semibold">Timestamp</p>
            <h3 class="truncate text-2xl leading-5">{{ transaction["timestamp"] }}</h3>
        </div>
        <div class="mb-3">
            <p class="text-gray-600 font-semibold">Data</p>
            <h3 class="truncate text-2xl leading-5">{{ transaction["data"] }}</h3>
        </div>
        <div class="mb-3">
            <p class="text-gray-600 font-semibold">Transaction's Signature</p>
            <h3 class="truncate text-2xl leading-5">{{ transaction["signature"] }}</h3>
        </div>
    </div>
</div>

{% endblock %}

dashboard/templates/valid_register.html
{% extends "base.html" %}
{% block content %}
<div class="max-w-4xl mx-auto p-3 my-10">
    <div class="flex items-center space-x-3">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8 text-green-600">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 0 1-1.043 3.296 3.745 3.745 0 0 1-3.296 1.043A3.745 3.745 0 0 1 12 21c-1.268 0-2.39-.63-3.068-1.593a3.746 3.746 0 0 1-3.296-1.043 3.745 3.745 0 0 1-1.043-3.296A3.745 3.745 0 0 1 3 12c0-1.268.63-2.39 1.593-3.068a3.745 3.745 0 0 1 1.043-3.296 3.746 3.746 0 0 1 3.296-1.043A3.746 3.746 0 0 1 12 3c1.268 0 2.39.63 3.068 1.593a3.746 3.746 0 0 1 3.296 1.043 3.746 3.746 0 0 1 1.043 3.296A3.745 3.745 0 0 1 21 12Z" />
        </svg>
        <h3 class="text-3xl">Registration Complete</h3>
    </div> 
    <div class="my-3">
        <p class="text-red-500 text-sm">Please keep your private key secured and do not share it with anyone.</p>
        <p class="font-mono bg-gray-100 rounded px-2 text-gray-600" id="private_key">{{private_key}}</p>    
    </div>
    <a href="{{ url_for('dashboard.index') }}" class="border px-5 py-1 rounded hover:bg-gray-100 ease duration-200">Continue</a>
</div>
{% endblock %}

dashboard/templates/view_transaction.html
{% extends "base.html" %}

{% block content %}
<div class="max-w-3xl mx-auto my-5">
    <a href="{{ url_for('dashboard.index') }}" class="border px-5 py-1 rounded hover:bg-gray-200 ease duration-200">Return</a>
    <div class="border p-3 my-5">
        <div class="mb-3">
            <p class="text-gray-600 font-semibold">Transaction Hash</p>
            <h3 class="truncate text-lg leading-5">{{ transaction["transaction_hash"] }}</h3>
        </div>
        <div class="mb-3">
            <p class="text-gray-600 font-semibold">Owner</p>
            <h3 class="truncate text-lg leading-5">{{ transaction["public_key"] }}</h3>
        </div>
        <div class="mb-3">
            <p class="text-gray-600 font-semibold">Timestamp</p>
            <h3 class="truncate text-lg leading-5">{{ transaction["timestamp"] }}</h3>
        </div>
        <div class="mb-3">
            <p class="text-gray-600 font-semibold">Data</p>
            <h3 class="truncate text-lg leading-5">{{ transaction["data"] }}</h3>
        </div>
        <div class="mb-3">
            <p class="text-gray-600 font-semibold">Transaction's Signature</p>
            <h3 class="truncate text-lg leading-5">{{ transaction["signature"] }}</h3>
        </div>
    </div>
</div>

{% endblock %}

dashboard/templates/vote.html
{% extends "base.html" %}
{% block content %}


<form class="max-w-7xl mx-auto" method="POST">
    {% if is_valid == true %}
        <div class="w-full p-3 my-5 rounded border border-green-500 bg-green-600 text-white">
            <p>Blockchain is valid.</p>
        </div>
    {% else %}
        <div class="w-full p-3 my-5 rounded border border-red-500 bg-red-600 text-white">
            <p>Blockchain is invalid.</p>
        </div>
    {% endif %}
    <div class="grid grid-cols-1 md:grid-cols-3 gap-2.5 my-5 md:mx-0 mx-2.5">
        
        {{ form.csrf_token() }}
        {% for subfield in form.candidates %}
        <label for="{{ subfield.id }}" class="border w-full p-4 rounded cursor-pointer has-[:checked]:bg-gray-100">
            {{ subfield(class="hidden") }}
            <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png" class="rounded-full h-32 d-block mx-auto">
            <h4 class="text-center mt-5">{{ subfield.label }}</h4>
        </label>
        {% endfor %}
    </div>
    {% for error in form.candidates.errors %}
        <p class="w-full mb-4 text-red-600 text-semibold">{{error}}</p>
    {% endfor %}
    <div class="flex justify-between items-center">
        {{ form.private_key(class="border border-gray-200 px-2.5 py-1 rounded w-64 focus:outline-none focus:border-gray-500", placeholder="Private Key") }}
        <div class="flex items-center space-x-5">
            <a href="{{ url_for('dashboard.register') }}" class="px-5 py-1 border bg-gray-100 hover:bg-gray-200 ease duration-200 rounded">Register</a>
            <a href="{{ url_for('dashboard.results') }}" class="px-5 py-1 border bg-gray-100 hover:bg-gray-200 ease duration-200 rounded">Results</a>
            {{ form.submit(class="border px-5 py-1 rounded bg-gray-100 hover:bg-gray-200 ease duration-200") }}
        </div>
    </div>
    
</form>

{% endblock %}

dashboard/templates/vote_added.html
{% extends "base.html" %}
{% block content %}

<div class="max-w-5xl border mx-auto p-3 my-5">
    
    <div class="flex items-center space-x-3">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8 text-green-600">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 0 1-1.043 3.296 3.745 3.745 0 0 1-3.296 1.043A3.745 3.745 0 0 1 12 21c-1.268 0-2.39-.63-3.068-1.593a3.746 3.746 0 0 1-3.296-1.043 3.745 3.745 0 0 1-1.043-3.296A3.745 3.745 0 0 1 3 12c0-1.268.63-2.39 1.593-3.068a3.745 3.745 0 0 1 1.043-3.296 3.746 3.746 0 0 1 3.296-1.043A3.746 3.746 0 0 1 12 3c1.268 0 2.39.63 3.068 1.593a3.746 3.746 0 0 1 3.296 1.043 3.746 3.746 0 0 1 1.043 3.296A3.745 3.745 0 0 1 21 12Z" />
        </svg>
        <h3 class="text-3xl">Your vote has been added to the chain.</h3>
    </div>  
    <div class="my-3">
        <p class="font-mono">Block Hash: {{ block_hash }}</p>
        <p class="font-mono">Transaction Hash: {{ transaction_hash }}</p>
        <a href='{{ url_for("dashboard.view_transaction", block_hash = block_hash, transaction_hash = transaction_hash) }}' class="text-blue-600 underline">View Transaction</a>
    </div>
</div>
{% endblock %}